[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
